
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  if Vagrant.has_plugin?("vagrant-hosts")
    config.vm.provision :hosts do |provisioner|
      provisioner.add_localhost_hostnames = false
      provisioner.autoconfigure = true
      provisioner.sync_hosts = true
      provisioner.add_host '192.168.10.10', ['chaordicapp']
    end
  end

  config.vm.box = "puppetlabs/ubuntu-16.04-64-puppet"

  # puppet server + puppet agent
  config.vm.define "chaordicapp" do |chaordicapp|
    puppetserver.vm.hostname = "chaordicapp.lab"
    puppetserver.vm.network :private_network, ip: "192.168.10.10"
    puppetserver.vm.provision "shell", path: "install.sh"
    puppetserver.vm.provider "virtualbox" do |v|
      v.customize [ "modifyvm", :id, "--cpus", "4" ]
      v.customize [ "modifyvm", :id, "--memory", "2048" ]
      v.customize [ "modifyvm", :id, "--name", "chaordicapp.lab" ]
    end
  end

end

